## Dam

1: Equipment_Dam:
nunique: 2
['Dam dispenser #1' 'Dam dispenser #2']
Equipment_Dam has no missing values

2: Model.Suffix_Dam:
nunique: 7
['AJX75334505' 'AJX75334501' 'AJX75334502' 'AJX75334507' 'AJX75334506'
 'AJX75334508' 'AJX75334503']
Model.Suffix_Dam has no missing values

3: Workorder_Dam:
nunique: 663
['4F1XA938-1' '3KPM0016-2' '4E1X9167-1' '3K1X0057-1' '3HPM0007-1'
 '3G1X8297-2' '3M1XH425-1' '4A1XB542-4' '3H1X9883-1' '3G1XD171-2'
 '4E1X9168-1' '4A1XC343-1' '3L1XA128-1' '3L1X8574-2' '3GPM0070-1'
 '3G1X4502-2' '3F1X9648-1' '4B1XA868-1' '3L1XB019-1' '4C1X0049-1'

 (중략)
 
 '4E1X9525-1' '3LPM0199-1' '4C1XH943-1' '3FPXX064-0003' '4B1XB835-3'
 '4C1XD447-1' '3LPM0200-1' '4B1X0039-1' '4C1XJ040-1' '4A1XE569-1'
 '3J1XG645-1' '3G1X8647-2' '3H1XC430-1' '3H1XB714-1' '4CPM0074-1'
 '3K1X9887-2' '3L1XB234-1' '3HPM0061-1']
Workorder_Dam has no missing values

4: CURE END POSITION X Collect Result_Dam:
nunique: 2
[ 240. 1000.]
CURE END POSITION X Collect Result_Dam has no missing values

5: CURE END POSITION Z Collect Result_Dam:
nunique: 2
[ 2.5 12.5]
CURE END POSITION Z Collect Result_Dam has no missing values

6: CURE END POSITION Θ Collect Result_Dam:
nunique: 2
[-90  90]
CURE END POSITION Θ Collect Result_Dam has no missing values

7: CURE SPEED Collect Result_Dam:
nunique: 5
[100  70  85  95 105]
CURE SPEED Collect Result_Dam has no missing values

8: CURE START POSITION X Collect Result_Dam:
nunique: 2
[1030  280]
CURE START POSITION X Collect Result_Dam has no missing values

9: CURE START POSITION Θ Collect Result_Dam:
nunique: 2
[-90  90]
CURE START POSITION Θ Collect Result_Dam has no missing values

10: DISCHARGED SPEED OF RESIN Collect Result_Dam:
nunique: 3
[16 10 15]
DISCHARGED SPEED OF RESIN Collect Result_Dam has no missing values

11: DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam:
nunique: 19
[14.9 21.3 14.7  9.7  9.6 13.2 14.2 13.6 17.  13.5 13.1 21.2 13.8 11.6
 14.8 14.3 17.1 13.7 10.6]
DISCHARGED TIME OF RESIN(Stage1) Collect Result_Dam has no missing values

12: DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam:
nunique: 29
[ 8.4  4.9  8.5  6.5  7.6  4.8  8.2 10.5  5.4  3.9  8.1  6.6  8.3  7.7
  6.7 10.6  5.   7.5  5.5  8.6  3.8  7.9  7.2  8.   4.   7.1  5.8  5.9
  6.9]
DISCHARGED TIME OF RESIN(Stage2) Collect Result_Dam has no missing values

13: DISCHARGED TIME OF RESIN(Stage3) Collect Result_Dam:
nunique: 20
[14.7 21.3  9.6  9.7 13.2 14.3 13.1 13.6 14.2 17.  17.1 13.5 13.8 21.2
 11.6 14.8 13.7  9.8 21.4 11.5]
DISCHARGED TIME OF RESIN(Stage3) Collect Result_Dam has no missing values

14: Dispense Volume(Stage1) Collect Result_Dam:
nunique: 23
[1.04 1.49 1.61 0.67 0.92 1.02 0.99 1.45 0.95 1.19 1.63 1.56 0.94 0.91
 1.48 0.96 1.44 0.81 1.03 1.62 1.   2.34 0.74]
Dispense Volume(Stage1) Collect Result_Dam has no missing values

15: Dispense Volume(Stage2) Collect Result_Dam:
nunique: 33
[0.58 0.34 0.93 0.45 0.53 0.33 0.59 0.57 0.73 0.37 0.27 0.56 0.72 0.92
 0.46 0.74 0.9  0.35 0.71 0.52 0.38 0.94 0.6  0.26 0.55 0.5  0.89 0.91
 0.28 0.49 0.4  0.41 0.48]
Dispense Volume(Stage2) Collect Result_Dam has no missing values

16: Dispense Volume(Stage3) Collect Result_Dam:
nunique: 22
[1.02 1.49 1.61 0.67 0.92 1.   1.44 0.95 0.99 1.19 0.91 1.45 1.56 0.94
 0.96 1.48 0.81 1.62 1.03 0.68 1.57 0.8 ]
Dispense Volume(Stage3) Collect Result_Dam has no missing values

17: HEAD NORMAL COORDINATE X AXIS(Stage1) Collect Result_Dam:
nunique: 36
[550.5 550.3 162.4 549.  550.4 162.7 161.7 164.2 550.6 551.5 551.3 549.5
 550.  161.2 551.7 552.  163.8 548.9 551.8 163.5 164.1 551.2 164.  163.3
 163.7 552.1 548.5 549.4 550.7 164.5 163.1 551.6 163.4 163.6 163.  551. ]
HEAD NORMAL COORDINATE X AXIS(Stage1) Collect Result_Dam has no missing values

18: HEAD NORMAL COORDINATE X AXIS(Stage2) Collect Result_Dam:
nunique: 38
[464.3  463.8  465.4  465.5  462.5  463.   463.7  465.7  464.7  467.1
 463.9  465.   464.6  463.5  464.2  462.75 465.3  465.6  466.8  462.2
 465.1  465.8  466.2  463.6  464.8  466.7  466.   466.9  462.7  464.
 467.5  466.1  464.9  466.3  466.6  467.2  466.5  466.4 ]
HEAD NORMAL COORDINATE X AXIS(Stage2) Collect Result_Dam has no missing values

19: HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Dam:
nunique: 36
[161.4 160.8 551.7 552.  159.5 160.5 161.3 551.  553.6 161.5 162.3 162.2
 160.  550.5 551.3 162.6 162.9 553.1 159.8 553.4 161.2 162.1 553.2 552.9
 553.  160.3 552.4 162.5 552.3 552.6 554.  553.7 552.7 161.9 551.1 552.2]
HEAD NORMAL COORDINATE X AXIS(Stage3) Collect Result_Dam has no missing values

20: HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Dam:
nunique: 14
[ 384.   377.3 1271.8  377.5  377.6 1271.3 1272.1 1269.  1281.  1281.2
 1281.8 1281.3 1273.8 1280.8]
HEAD NORMAL COORDINATE Y AXIS(Stage1) Collect Result_Dam has no missing values

21: HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Dam:
nunique: 15
[ 383.1  377.3 1383.9 1270.7  377.   377.1 1268.4 1393.5 1393.7 1268.2
 1268.8 1394.2 1393.4 1273.2 1392.9]
HEAD NORMAL COORDINATE Y AXIS(Stage2) Collect Result_Dam has no missing values

22: HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Dam:
nunique: 16
[ 384.   377.3 1271.8  377.5  377.6  378.  1271.3 1272.1 1269.  1281.2
 1281.4 1282.  1281.3 1281.5 1273.8 1280.8]
HEAD NORMAL COORDINATE Y AXIS(Stage3) Collect Result_Dam has no missing values

23: HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Dam:
nunique: 24
[274.51  282.15  274.33  284.8   282.5   280.894 273.8   282.361 274.4
 274.2   281.324 282.343 274.    281.413 284.6   281.095 281.226 274.78
 281.222 281.517 281.43  281.3   281.513 281.424]
HEAD NORMAL COORDINATE Z AXIS(Stage1) Collect Result_Dam has no missing values

24: HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Dam:
nunique: 24
[274.51  282.15  274.33  284.8   282.5   280.894 273.8   282.361 274.4
 274.2   281.324 282.343 274.    281.413 284.6   281.095 281.226 274.78
 281.222 281.517 281.43  281.3   281.513 281.424]
HEAD NORMAL COORDINATE Z AXIS(Stage2) Collect Result_Dam has no missing values

25: HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Dam:
nunique: 24
[274.51  282.15  274.33  284.8   282.5   280.894 273.8   282.361 274.4
 274.2   281.324 282.343 274.    281.413 284.6   281.095 281.226 274.78
 281.222 281.517 281.43  281.3   281.513 281.424]
HEAD NORMAL COORDINATE Z AXIS(Stage3) Collect Result_Dam has no missing values

26: Head Clean Position Z Collect Result_Dam:
nunique: 5
[124.   130.85 133.5  124.5  118.85]
Head Clean Position Z Collect Result_Dam has no missing values

27: Head Purge Position Z Collect Result_Dam:
nunique: 3
[130.85 133.5  124.5 ]
Head Purge Position Z Collect Result_Dam has no missing values

28: Head Zero Position Y Collect Result_Dam:
nunique: 2
[300.  303.5]
Head Zero Position Y Collect Result_Dam has no missing values

29: Head Zero Position Z Collect Result_Dam:
nunique: 2
[265.   265.02]
Head Zero Position Z Collect Result_Dam has no missing values

30: Machine Tact time Collect Result_Dam:
nunique: 457
[ 58.5  65.1  76.9  70.5  88.3  93.3  53.5  57.8  88.2  88.4  76.8  58.3
  72.6  67.4  92.3  92.2  57.1  53.9  55.9  57.   60.5  54.8  76.6  56.7
  54.9  55.8  58.4  93.2  57.6  59.3  77.   59.   57.9  56.8  68.9  92.1
  72.7  58.   56.3  53.8  72.4  80.   54.7  71.3  70.9  71.   60.7  58.1
  69.   54.3  66.9  72.3  56.5  77.1  57.7  74.5  71.2  76.2  59.4  72.1
  72.5  59.1  75.3  88.5  71.6  56.2  53.6  67.   53.7  66.4  77.2  75.
  53.4  65.3  56.6  71.8  71.1  75.1  57.5  61.8  54.2  72.9  76.7  70.3
  69.4  72.8  52.9  76.1  60.4  49.8  72.   71.5  72.2  71.4  73.5  61.4
  54.1  75.9  56.4  58.8  73.6  73.1  60.3  52.1  74.8  71.7  53.   70.7
  91.2  58.6  56.9  56.   87.2  65.6  78.3  59.8  58.7  73.   65.2  74.9
  69.2  75.7  70.8  73.3  93.4  83.3  92.   54.5  70.4  65.4  68.8  53.3
  64.9  54.6  51.7  66.   73.2  71.9  74.7  76.3  79.3  55.   50.3  70.
  60.2  55.1  58.2  89.   59.7  59.2  52.   69.6  68.   62.   54.4  70.1
  93.1  59.5  76.   83.4  56.1  50.7  61.7  62.1  69.5  67.7  69.3  70.2
  60.6  88.7  54.   66.2 104.1  66.8  58.9  75.8  61.6 104.  157.2  74.6
  67.1  57.2  60.1  55.6  88.9  52.6  52.8  65.8  63.   87.1  50.2  61.5
  68.7  70.6  88.8  78.5  64.5  91.1  60.9 102.   75.2  46.3  67.2  78.4
  67.3  66.7  62.9  51.8  52.5  78.6  65.9  44.4  78.1  69.1  59.6  93.5
  75.6  61.9  66.3  55.7  73.8  65.7  62.2  92.4  85.1  51.9  95.4  69.7
  77.6  61.1  65.5  79.4  76.4  74.4  73.7  65.   50.   87.   55.4  77.3
  49.9  76.5  60.8  95.6  79.2  78.2  79.7  91.3  66.1  68.1  77.4  55.5
 103.9  55.3  51.1  60.   73.9  73.4  93.7  63.8  77.7  50.5  68.5  53.2
  53.1  61.3  75.5  66.6  50.1  50.4  67.5  74.3  79.6  63.9  55.2  83.2
  48.5  57.4  69.9  95.3 175.6  50.6  84.7  66.5  89.1 120.8  52.4  64.3
  89.6  94.1  74.   87.3  75.4  52.3  67.6  88.6  79.5  68.4  68.6  51.5
  68.2  48.2  50.9  57.3 111.5  69.8  85.7  35.6  88.1  79.9  64.4 132.8
  51.2  82.4  52.2  95.5 127.   50.8  78.7  78.9  63.7 239.9 140.5  64.7
 103.   44.9  78.8  48.1  44.8  89.9 243.1  67.9 101.4 177.   80.1  68.3
  77.5  92.6 153.6 101.9  47.7  61.2 104.2  59.9  95.2  44.6  64.1  63.1
  45.6  78.   47.8  45.1  64.6  83.5  63.2  48.3  51.   47.6  81.   87.8
  90.   35.5  92.5  61.   84.1  46.   46.1  51.6  48.6 123.2  86.4  79.8
  95.7 362.3 111.7  67.8  89.4  84.5  45.9 101.6 111.6  74.1 523.   45.
 161.2 187.9 197.3  63.5  98.5  81.3  63.3 212.9  99.8  62.7  44.5  49.6
  89.3  46.4 243.8  64.2  84.   63.6  62.4  85.6 101.5 244.7  87.4 156.2
 999.9 135.4  62.8  64.8  51.4  91.5  48.   48.4  62.5 100.4  89.8 283.7
  64.   83.1  40.6  74.2  47.5  84.2  80.5  86.   80.8 169.8  47.4  44.7
 100.8  52.7  79.1 209.   46.2  62.6  86.3  77.9 156.1  85.5  51.3  80.6
 148.8 139.6  84.9 133.7  46.7 276.6  49.1  81.4  96.1  62.3 119.2  99.6
 110.5]
Machine Tact time Collect Result_Dam has no missing values

31: PalletID Collect Result_Dam:
nunique: 16
[ 7. 10. 12.  8. 11.  3.  6. 15. 16.  1.  4.  5.  2. 14.  9. 13.]
PalletID Collect Result_Dam has no missing values

32: Production Qty Collect Result_Dam:
nunique: 607
[127 185  73 268 121 343 483 105  95 353  78 221  89 132 146 109 134  77
 225 219  45 209 106  71 195 161 116 114 152 336 272 299  21 151  12 235
 122 279 111 371   8 196 143 237 144 160 129 177 135 253 187 147 391 197
 110 291 216 179 223 282 200 323 413 321 247 464 284 123  60 324  48 170
 416  94 271  25 302 335 350  19  11 317  80 262 128 327 205 339 156   4
 166 300  47  75  46 258 180  82  38 139 289 338 274 125  50 104 261 210
 331  49 213 245  64 265 217 102 175  36 181  52  23   2 515 363  69 397
 193 368 163  92 449  67 259  68 243 380  15 174  56 309  87  53 199 267
 171 345 173 277 328 184 240 298  90  96 425 112 288 137 159 301 307 384
  20 452  99 182 297 466  24 295 211   0 107  35 290  10  39 292 228 251
 115 521  28 138 194  97 203  72 346  76 427 244  42 377 250 276  55 167
 257 420 162 118 158  16 422 108 503  32 280 202  18  74 308   5 150 459
 234 311  54 376  79 183 393  57 130 164 423  84 198 580 278  51 313  44
 372 239 546 269 467  34 518  37  88  61 316 348 148 390 191  26 419 224
  22  29  27 340 360  91 149 117 410 153 400   6 296  33 172 227  43 238
 231  59  98  40 126 322   7 168 401  83 204 285 165 229  13 429 431  70
 388 373 120 355 233 294 212 186 273 266 283 220 314 306 329 319 457  86
 190 176 365 142 113 304 349 538 310  31 207 399 312 256 354 169 482 260
 557 242 208 351 206  58 254 434  17 215  81 359 496 476 255 281 389 155
 226 381 192 131 469 315 287 101 188 432 409 344 136 124   3 178 230 428
  62 405 236 100 222 252 241 341 318  30 435 270 145 404 364 332 477 472
 333 374 548 450 501  93  41 141 417 246 361 568 356 103 596 157 342 379
 305 263 547 140 408 286 320 412 303 406 248 119  14 133 218 396 154  85
 367 592 458 334  63 487 475 275 415 189   1 473 357 232  65 386 201 330
 249 430 542 448 293 347 392 370 383 529 453 369 447 366 398 444 522 325
 474   9 326 436 395 602 337 418 385 402 511 264 375 362 603 493 460 461
  66 502 523 378 465 456 358 445 214 387 438 489 437 520 486 411 541 481
 463 504 414 601 442 451 545 485 421 590 565 508 480 587 382 424 558 407
 491 394 352 555 443 462 426 468 497 530 498 528 567 484 446 513 440 510
 495 439 471 454 433 524 526 517 403 455 583 441 506 571 479 533 600 470
 494 536 581 563 490 527 577 519 552 531 507 505 561 570 514 525 478 550
 488 512 574 604 534 608 535 559 569 573 499 554 598 566 540 589 500 607
 582 562 560 594 492 543 591 579 585 564 544 537 597 586 599 549 572 584
 553 516 593 588 575 551 532 556 578 509 606 605 576]
Production Qty Collect Result_Dam has no missing values

33: Receip No Collect Result_Dam:
nunique: 5
[ 1  6 17  9  3]
Receip No Collect Result_Dam has no missing values

34: Stage1 Circle1 Distance Speed Collect Result_Dam:
nunique: 7
[5800 4000 9000 6500 6000 5000 6200]
Stage1 Circle1 Distance Speed Collect Result_Dam has no missing values

35: Stage1 Circle2 Distance Speed Collect Result_Dam:
nunique: 7
[5800 4000 9000 6500 6000 5000 6200]
Stage1 Circle2 Distance Speed Collect Result_Dam has no missing values

36: Stage1 Circle3 Distance Speed Collect Result_Dam:
nunique: 7
[5800 4000 9000 6500 6000 5000 6200]
Stage1 Circle3 Distance Speed Collect Result_Dam has no missing values

37: Stage1 Circle4 Distance Speed Collect Result_Dam:
nunique: 7
[5800 4000 9000 6500 6000 5000 6200]
Stage1 Circle4 Distance Speed Collect Result_Dam has no missing values

38: Stage1 Line1 Distance Speed Collect Result_Dam:
nunique: 9
[ 5800  4000  9000  6500  6000  5000  6200  7000 13000]
Stage1 Line1 Distance Speed Collect Result_Dam has no missing values

39: Stage1 Line2 Distance Speed Collect Result_Dam:
nunique: 7
[5800 4000 9000 6500 6000 5000 6200]
Stage1 Line2 Distance Speed Collect Result_Dam has no missing values

40: Stage1 Line3 Distance Speed Collect Result_Dam:
nunique: 9
[5600 4000 5800 9000 6500 6000 5000 6200 7000]
Stage1 Line3 Distance Speed Collect Result_Dam has no missing values

41: Stage1 Line4 Distance Speed Collect Result_Dam:
nunique: 7
[5800 4000 9000 6500 6000 5000 6200]
Stage1 Line4 Distance Speed Collect Result_Dam has no missing values

42: Stage2 Circle1 Distance Speed Collect Result_Dam:
nunique: 9
[ 5300  9000  5000  6500  5500  4000  8000 12000  6000]
Stage2 Circle1 Distance Speed Collect Result_Dam has no missing values

43: Stage2 Circle2 Distance Speed Collect Result_Dam:
nunique: 9
[ 5300  9000  5000  6500  5500  4000  8000 12000  6000]
Stage2 Circle2 Distance Speed Collect Result_Dam has no missing values

44: Stage2 Circle3 Distance Speed Collect Result_Dam:
nunique: 9
[ 5300  9000  5000  6500  5500  4000  8000 12000  6000]
Stage2 Circle3 Distance Speed Collect Result_Dam has no missing values

45: Stage2 Circle4 Distance Speed Collect Result_Dam:
nunique: 9
[ 5300  9000  5000  6500  5500  4000  8000 12000  6000]
Stage2 Circle4 Distance Speed Collect Result_Dam has no missing values

46: Stage2 Line1 Distance Speed Collect Result_Dam:
nunique: 9
[ 5300  9000  5000  6500  5500  4000  8000 12000 13000]
Stage2 Line1 Distance Speed Collect Result_Dam has no missing values

47: Stage2 Line2 Distance Speed Collect Result_Dam:
nunique: 10
[ 5300  9000  5000  6500  5500  4000  8000 12000  6000  5800]
Stage2 Line2 Distance Speed Collect Result_Dam has no missing values

48: Stage2 Line3 Distance Speed Collect Result_Dam:
nunique: 9
[ 5300  9000  5000  6500  5500  4000  8000 12000  6000]
Stage2 Line3 Distance Speed Collect Result_Dam has no missing values

49: Stage2 Line4 Distance Speed Collect Result_Dam:
nunique: 10
[ 5300  9000  5000  6500  5500  4000  8000 12000  6000  5800]
Stage2 Line4 Distance Speed Collect Result_Dam has no missing values

50: Stage3 Circle1 Distance Speed Collect Result_Dam:
nunique: 7
[5800 4000 9000 6500 6000 5000 6200]
Stage3 Circle1 Distance Speed Collect Result_Dam has no missing values

51: Stage3 Circle2 Distance Speed Collect Result_Dam:
nunique: 7
[5800 4000 9000 6500 6000 5000 6200]
Stage3 Circle2 Distance Speed Collect Result_Dam has no missing values

52: Stage3 Circle3 Distance Speed Collect Result_Dam:
nunique: 7
[5800 4000 9000 6500 6000 5000 6200]
Stage3 Circle3 Distance Speed Collect Result_Dam has no missing values

53: Stage3 Circle4 Distance Speed Collect Result_Dam:
nunique: 7
[5800 4000 9000 6500 6000 5000 6200]
Stage3 Circle4 Distance Speed Collect Result_Dam has no missing values

54: Stage3 Line1 Distance Speed Collect Result_Dam:
nunique: 8
[5800 4000 9000 6500 6000 5000 6200 7000]
Stage3 Line1 Distance Speed Collect Result_Dam has no missing values

55: Stage3 Line2 Distance Speed Collect Result_Dam:
nunique: 7
[5800 4000 9000 6500 6000 5000 6200]
Stage3 Line2 Distance Speed Collect Result_Dam has no missing values

56: Stage3 Line3 Distance Speed Collect Result_Dam:
nunique: 8
[5800 4000 9000 6500 6000 5000 6200 7000]
Stage3 Line3 Distance Speed Collect Result_Dam has no missing values

57: Stage3 Line4 Distance Speed Collect Result_Dam:
nunique: 7
[5800 4000 9000 6500 6000 5000 6200]
Stage3 Line4 Distance Speed Collect Result_Dam has no missing values

58: THICKNESS 1 Collect Result_Dam:
nunique: 7
[ 0.     0.012 -0.054  0.014 -0.015 -0.019  0.037]
THICKNESS 1 Collect Result_Dam has no missing values

59: THICKNESS 2 Collect Result_Dam:
nunique: 8
[ 0.    -0.022 -0.219 -0.058  0.007 -0.036 -0.021  0.005]
THICKNESS 2 Collect Result_Dam has no missing values

60: THICKNESS 3 Collect Result_Dam:
nunique: 7
[ 0.     0.003  0.007  0.012 -0.026 -0.118  0.024]
THICKNESS 3 Collect Result_Dam has no missing values

In [ ]:
import pandas as pd
import numpy as np

train_second = pd.read_csv("./data/train_second.csv")

In [ ]:
# train_second 데이터프레임에서 CURE END POSITION X Collect Result_Dam 값이 21000 행만 추출
train_second_240 = train_second[train_second['CURE END POSITION X Collect Result_Dam'] == 240]

# train_second 데이터프레임에서 CURE END POSITION X Collect Result_Dam 값이 1000인 행만 추출
train_second_1000 = train_second[train_second['CURE END POSITION X Collect Result_Dam'] == 1000]

In [ ]:
# train_second_240 데이터프레임에서 모든 데이터 값이 같은 열 확인
train_second_240.columns[train_second_240.nunique() == 1]

In [30]:
train_second_1000

Equipment_Dam Model.Suffix_Dam Workorder_Dam  \
2      Dam dispenser #2      AJX75334501    4E1X9167-1   
3      Dam dispenser #2      AJX75334501    3K1X0057-1   
7      Dam dispenser #2      AJX75334501    4A1XB542-4   
10     Dam dispenser #2      AJX75334501    4E1X9168-1   
11     Dam dispenser #2      AJX75334501    4A1XC343-1   
...                 ...              ...           ...   
40491  Dam dispenser #2      AJX75334501    3K1X8037-1   
40492  Dam dispenser #2      AJX75334501    3K1XB238-2   
40500  Dam dispenser #2      AJX75334501    3L1XA128-1   
40502  Dam dispenser #2      AJX75334501    4E1XC796-1   
40504  Dam dispenser #2      AJX75334501    3I1XA258-1   

       CURE END POSITION X Collect Result_Dam  \
2                                      1000.0   
3                                      1000.0   
7                                      1000.0   
10                                     1000.0   
11                                     1000.0   
...                                       ...   
40491                                  1000.0   
40492                                  1000.0   
40500                                  1000.0   
40502                                  1000.0   
40504                                  1000.0   

       CURE END POSITION Z Collect Result_Dam  \
2                                        12.5   
3                                        12.5   
7                                        12.5   
10                                       12.5   
11                                       12.5   
...                                       ...   
40491                                    12.5   
40492                                    12.5   
40500                                    12.5   
40502                                    12.5   
40504                                    12.5   

       CURE END POSITION Θ Collect Result_Dam  CURE SPEED Collect Result_Dam  \
2                                          90                             85   
3                                          90                             70   
7                                          90                             70   
10                                         90                             85   
11                                         90                             70   
...                                       ...                            ...   
40491                                      90                             70   
40492                                      90                             70   
40500                                      90                             70   
40502                                      90                            100   
40504                                      90                             70   

       CURE START POSITION X Collect Result_Dam  \
2                                           280   
3                                           280   
7                                           280   
10                                          280   
11                                          280   
...                                         ...   
40491                                       280   
40492                                       280   
40500                                       280   
40502                                       280   
40504                                       280   

       CURE START POSITION Θ Collect Result_Dam  \
2                                            90   
3                                            90   
7                                            90   
10                                           90   
11                                           90   
...                                         ...   
40491                                        90   
40492                                        90   
40500                                        90   
40502                                        90   


In [ ]:
# train_second_1000 데이터프레임에서 모든 데이터 값이 같은 열 확인
train_second_1000.columns[train_second_1000.nunique() == 1]

In [ ]:
# train_second 데이터프레임에서 CURE END POSITION X Collect Result_Fill2 값이 21000 행만 추출
train_second_240 = train_second[train_second['CURE END POSITION X Collect Result_Fill2'] == 240]

# train_second 데이터프레임에서 CURE END POSITION X Collect Result_Fill2 값이 1000인 행만 추출
train_second_1020 = train_second[train_second['CURE END POSITION X Collect Result_Fill2'] == 1020]

In [ ]:
# train_second_240 데이터프레임에서 모든 데이터 값이 같은 열 확인
train_second_240.columns[train_second_240.nunique() == 1]

In [ ]:
# train_second_1020 데이터프레임에서 모든 데이터 값이 같은 열 확인
train_second_1020.columns[train_second_1020.nunique() == 1]

In [ ]:
train_second_1020

In [ ]:
# train_second_1020 데이터프레임에서 모든 데이터 값이 같은 열을 모두 포함한 후 데이터프레임 생성
train_second_1020_same = train_second_1020[train_second_1020.columns[train_second_1020.nunique() == 1]]
train_second_1020_same

# train_second_1020_same과 train_second_1020의 'target'열을 concat하여 데이터프레임 생성
train_second_1020_same = pd.concat([train_second_1020_same, train_second_1020['target']], axis=1)

# train_second_1020과 train_seconde


In [ ]:
train_second_1020_same

In [ ]:
train_second_1020_same['target'].value_counts()